package springboot.ToDo.Model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Entity
@NoArgsConstructor
@Table(name = "todo_user_profiles1" , schema = "sumit")
public class UserProfile_pg1 {



    public UserProfile_pg1(UserAuth userAuth, int uid, String username, Sex sex) {
        this.userAuth = userAuth;
        this.uid = uid;
        this.username = username;
        this.sex = sex;
    }

    public UserProfile_pg1(String username) {
        this.username = username;
    }

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "username", referencedColumnName ="username", insertable = false, updatable = false, nullable = false, unique = false )
    private UserAuth userAuth;


//    @Id
//    @GeneratedValue(strategy = GenerationType.UUID)
//                // The UUID will be automatically generated by Spring Boot & JPA when you save a new entity.
//    @Column(name = "uid", nullable = false, unique = true, updatable = false)
//    private UUID uid;  // The UUID will be automatically generated by Spring Boot & JPA when you save a new entity.


    @Id
    @GeneratedValue(strategy =GenerationType.IDENTITY)
    @Column(name = "uid", nullable = false, unique = true, updatable = false)
    @NotNull
    private int uid;


    @NotNull
    @Email(message = "ONLY emails allowed as USERNAME")
    @Column(name="username", unique = true, nullable = false )
    private String username;



        public enum Sex{
            MALE, FEMALE
        }

    @Enumerated(EnumType.STRING) // ✅ Stores as "MALE" or "FEMALE"
        //This ensures the enum values are stored as "MALE" or "FEMALE" in the database instead of numbers (default behavior of JPA).
        @Column(name = "sex", nullable = true)
        private Sex sex;


    public int getUid() {
        return uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    public UserAuth getUserAuth() {
        return userAuth;
    }

    public void setUserAuth(UserAuth userAuth) {
        this.userAuth = userAuth;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Sex getSex() {
        return sex;
    }

    public void setSex(Sex sex) {
        this.sex = sex;
    }

    @Override
    public String toString() {
        return "UserProfile_pg1{" +
                "userAuth=" + userAuth +
                ", uid=" + uid +
                ", username='" + username + '\'' +
                ", sex=" + sex +
                '}';
    }
}
